os:
  - linux

php:
  - 7.2
  - 7.3

before_install:
  - sudo apt-get update
  - composer self-update
  - composer install --prefer-dist --no-interaction --optimize-autoloader --no-suggest
  - yarn

before_script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    chmod +x ./cc-test-reporter;
    fi
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    ./cc-test-reporter before-build;
    fi

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - yarn run test